apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-pdb
  labels:
    app: {{ .Chart.Name }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
