apiVersion: apps/v1
kind: Deployment
metadata:
  name: bobrossbot
  namespace: bobrossbot
  labels:
    app: bobrossbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bobrossbot
  template:
    metadata:
      labels:
        app: bobrossbot
    spec:
      containers:
      - name: bobrossbot
        image: bobrossbot:latest
        ports:
        - containerPort: 3000
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: bobrossbot-secrets
              key: DISCORD_TOKEN
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: bobrossbot-secrets
              key: OPENAI_API_KEY